config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#index'

  resources :factions do # resources :faction, path: 'teams' to change url
    resources :strategies, except: [:show, :edit, :new]
  end

  resources :great_old_ones

  resource :user
  get 'sign_up', action: :new, controller: 'users'
  get 'profile', action: :show, controller: 'users'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get 'profile/factions/edit', to: 'user_factions#edit'
  get 'profile/factions/:faction_id', to: 'user_factions#show'
  patch '/profile/factions', to: 'user_factions#update'

  namespace :admin do
    get '/dashboard', to: "dashboard#index"
    resources :game_days, only: [:create, :destroy, :update]
  end

  patch '/can_attends', to: 'can_attends#update'

  get '/join_team', to: 'teams#edit'
  get '/teams/:id', to: 'teams#show'
  patch '/teams/:id', to: 'teams#update'

end

# resource (singular)
# use strategies over user_strategies since we are never showing more than 1 users strategies
# un-nest strategies since only ever using 1 user at a time
# faction strategy takes over for user strategies
#

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/can_attend.rb
class CanAttend < ApplicationRecord
  belongs_to :game_day
  belongs_to :user
end

app/models/cultist.rb
class Cultist < ApplicationRecord
  belongs_to :faction
end

app/models/faction.rb
class Faction < ApplicationRecord
  has_many :great_old_ones, dependent: :destroy
  has_many :cultists, dependent: :destroy
  has_many :spellbooks, dependent: :destroy
  has_many :spellbook_requirements, dependent: :destroy
  has_many :monsters, dependent: :destroy

  has_many :user_factions
  has_many :users, through: :user_factions
end

app/models/game_day.rb
class GameDay < ApplicationRecord
  validates_presence_of :day, require: true

  has_many :can_attends, dependent: :destroy
  has_many :users, through: :can_attends

  def formatted
    day.strftime("%b %d at %I:%M%p")
  end

  def can_attend
    format_names(users)
  end

  def cannot_attend
    cannot = User.all.select do |user|
      !users.include?(user)
    end
    format_names(cannot)
  end

  def format_names(user_objs)
    user_objs.map(&:username).to_sentence
  end

  def self.days
    GameDay.order(:day)
  end
end

app/models/great_old_one.rb
class GreatOldOne < ApplicationRecord
  belongs_to :faction

  scope :ordered, -> {
    order(:name)
  }

  def steps_to_awaken
    awaken_steps.split("\n")
  end
end

app/models/membership.rb
class Membership < ApplicationRecord
  belongs_to :user
  belongs_to :team
end

app/models/monster.rb
class Monster < ApplicationRecord
  belongs_to :faction
end

app/models/spellbook.rb
class Spellbook < ApplicationRecord
  belongs_to :faction
end

app/models/spellbook_requirement.rb
class SpellbookRequirement < ApplicationRecord
  belongs_to :faction
end

app/models/strategy.rb
class Strategy < ApplicationRecord
  belongs_to :user
  belongs_to :faction
end

app/models/team.rb
class Team < ApplicationRecord
  has_secure_password

  has_many :memberships, dependent: :destroy
  has_many :users, through: :memberships
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, uniqueness: true, presence: true
  validates_presence_of :password, require: true
  validates_confirmation_of :password, on: :create

  has_secure_password

  enum role: %w(pleb admin)

  has_many :user_factions, dependent: :destroy
  has_many :factions, through: :user_factions

  has_many :can_attends, dependent: :destroy
  has_many :game_days, through: :can_attends

  has_many :strategies, dependent: :destroy

  has_many :memberships, dependent: :destroy
  has_many :teams, through: :memberships

  def liked_factions
    factions.order(:name)
  end
end

app/models/user_faction.rb
class UserFaction < ApplicationRecord
  belongs_to :user
  belongs_to :faction
end

app/controllers/factions_controller.rb
class FactionsController < ApplicationController
  def index
    @factions = Faction.all
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def show
    @faction = Faction.find(params[:id])
  end

  def destroy
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by("LOWER(users.username) LIKE LOWER('%#{params[:username]}%')")
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:success] = "Welcome, #{user.username}!"

      redirect_to '/'
    else
      flash[:alert] = 'Sorry, no matching account.'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil

    redirect_to '/'
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  def show
  end

  def edit
    @team = Team.first
  end

  def update
    team = Team.first
    if team.authenticate(params[:password])
      session[:validated] = true

      flash[:notice] = 'Welcome to the team! '
      redirect_to root_path
    else
      flash[:alert] = 'Invalid Password'

      render :edit
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def new
    if !session[:validated]
      flash[:alert] = 'You must join the team before creating an account'
      redirect_to root_path
    end
  end

  def create
    new_user = User.create(user_params)
    if new_user.validate && session[:validated]
      flash[:success] = "Welcome #{new_user.username}!"
      session[:user_id] = new_user.id

      redirect_to root_path
    else
      flash[:alert] = 'Invalid loggin.'
      render :new
    end
  end

  def edit
  end

  def update
  end

  def show
    @user = current_user
  end

  def destroy
  end

  private

  def user_params
    params.permit(:username, :password, :password_confirmation)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    if current_user
      @game_days = GameDay.days
    else
      redirect_to '/join_team'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">

    <title>Cthulhu Wars!</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>
  <body>
    <%= render 'partials/navbar' %>
    <div class="container">
      <%= render 'partials/flash' %>
      <br/>
      <%= yield %>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script>
  </body>
</html>

app/views/partials/_flash.html.erb
<% if flash[:success] %>
  <div class="alert alert-success mt-4" role="alert">
    <%= flash[:success] %>
  </div>
<% end %>

<% if flash[:notice] %>
  <div class="alert alert-info mt-4" role="alert">
    <%= flash[:notice] %>
  </div>
<% end %>

<% if flash[:alert] %>
  <div class="alert alert-warning mt-4" role="alert">
    <%= flash[:alert] %>
  </div>
<% end %>

<% if flash[:danger] %>
  <div class="alert alert-danger mt-4" role="alert">
    <%= flash[:danger] %>
  </div>
<% end %>

app/views/partials/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to 'Cthulhu Wars Home', '/', class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <div class="navbar-nav">
        <%= link_to 'Factions', factions_path, class: 'nav-link' %>
        <%= link_to 'Great Old Ones', '/great_old_ones', class: 'nav-link' %>
      </div>
      <div class="navbar-nav ms-auto">
        <% if current_user %>
          <%= link_to 'Profile', '/profile', class: 'nav-link' %>
          <%= link_to 'Admin Dashboard', '/admin/dashboard', class: 'nav-link' if current_admin? %>
          <%= link_to 'Logout', '/logout', method: :delete, class: 'nav-link' %>
        <% else %>
          <%= link_to 'Log In', '/login', class: 'nav-link' %>
          <%= link_to 'Sign Up', '/sign_up', class: 'nav-link' %>
        <% end %>
      </div>
    </div>
  </div>
</nav>